name: Makefile CI

on:
  push:
    branches: [ "vnd_x657b_h6117-user-11-RP1A.200720.011-164723-release-keys" ]
  pull_request:
    branches: [ "vnd_x657b_h6117-user-11-RP1A.200720.011-164723-release-keys" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
